services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    volumes: # volume used to persist data
      - pg:/var/lib/postgresql/data
    networks:
      - db
    restart: always

volumes: # volume creation
  pg: {}

networks:
  db:
    driver: bridge